### ISSUE TITLE
Bottomsheet close() not working

### ISSUE THREAD

**Issue by webnizam** [ParkGwangBeom/Sheet#3]
I appreciate developer for creating this useful library for iOS.

It seems like there is no way to dismiss the sheet from the screen once it become active.
I tried these methods below,

**close()
sheetNavigationController?.close()
navigationController?.popViewController(animated: true)**

none of them seems working, and the black color behind the sheet seems a bit weird.
It suppose to be transparent i think.

**Comment by ParkGwangBeom** [comment]
@webnizam 
Have you run on the example project included with open source?
If the code is executed in a new project, make sure to present the SheetNavigationController.
